version: "1.0"

services:
  loms:
    build: ./loms
    ports:
      - "8083:8083"
      - "8084:8084"

  cart:
    build: ./cart
    ports:
      - "8080:8080"
    depends_on:
      - products
      - loms

  products:
    image: gitlab-registry.ozon.dev/go/classroom-20/students/homework-draft/products:latest
    ports:
      - "8082:8082"