volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  cart:
    image: cart
    build: ./cart
    ports:
      - "8080:8080"
    depends_on:
      - products
      - loms

  products:
    image: gitlab-registry.ozon.dev/go/classroom-20/students/homework-draft/products:latest
    ports:
      - "8082:8082"

  loms:
    image: loms
    build: ./loms
    ports:
      - "8083:8083"
      - "8084:8084"
    depends_on:
      postgres-master:
        condition: service_healthy
      migration:
          condition: service_started
      kafka:
        condition: service_healthy
      kafka-init-topics:
        condition: service_completed_successfully

  notifier:
    image: notifier
    build: ./notifier
    depends_on:
      loms:
        condition: service_started
      kafka-init-topics:
          condition: service_completed_successfully

  postgres-master:
    image: postgresmasterloms:latest
    container_name: postgresmaster
    environment:
      - POSTGRES_USERNAME=loms-user
      - POSTGRES_PASSWORD=loms-password
      - POSTGRES_DATABASE=loms_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USERNAME -d $$POSTGRES_DATABASE" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    image: gomicro/goose:3.7.0
    depends_on:
      postgres-master:
        condition: service_healthy
    volumes:
      - ./loms/migrations:/migrations
    command: [ "goose", "-dir", "/migrations", "postgres", "host=postgres-master user=loms-user password=loms-password dbname=loms_db sslmode=disable", "up" ]

  prometheus:
    image: prom/prometheus:latest
    depends_on:
      - cart
      - loms
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    volumes:
      - ./grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "6831:4318"

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    hostname: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    healthcheck:
      test: ["CMD-SHELL", "cub kafka-ready -b kafka:29092 1 30"]
      interval: 2s
      timeout: 5s
      retries: 5

  kafka-init-topics:
    image: confluentinc/cp-kafka:7.7.1
    depends_on:
      kafka:
        condition: service_healthy
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
      cub kafka-ready -b kafka:29092 1 30 && \
      kafka-topics --create --topic loms.order-events --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka:29092'"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - 8085:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: "true"