cart-service:
  host: 0.0.0.0
  port: 8080
  workers: 5

loms-service:
  host: localhost
  grpc_port: 8083
  http_port: 8084

db_master:
  host: localhost
  port: 5432
  user: loms-user
  password: loms-password
  db_name: loms_db

db_replica:
  host: localhost
  port: 5433
  user: loms-user
  password: loms-password
  db_name: loms_db

kafka:
  host: localhost
  port: 29092
  order_topic: loms.order-events
  brokers: localhost:9092

jaeger:
  host: localhost
  port: 6831

product_service:
  host: http://localhost
  port: 8082
  token: testToken
  limit: 10
  burst: 10

