service:
  host: 0.0.0.0
  port: 8080
  workers: 5

jaeger:
  host: localhost
  port: 6831

product_service:
  host: http://products
  port: 8082
  token: testToken
  limit: 10
  burst: 10

loms_service:
  host: loms
  port: 8083
