service:
  host: 0.0.0.0
  grpc_port: 8083
  http_port: 8084

jaeger:
  host: localhost
  port: 6831

db_master:
  host: postgres-master
  port: 5432
  user: loms-user
  password: loms-password
  db_name: loms_db

db_replica:
  host: localhost
  port: 5433
  user: loms-user
  password: loms-password
  db_name: loms_db

kafka:
  host: localhost
  port: 29092
  order_topic: loms.order-events
  brokers: localhost:9092

